# VERSION=latest
# ENV=dev
# ENABLE_BUILD=false

version: "3.6"

services:

  app-cv-backend:
    image: registry.gitlab.com/oneprofile/app-cv-backend:${VERSION}
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        ENV:  ${ENV}
    container_name: cvbackend
    hostname: cvbackend
    networks:
      internal-subnet:
        ipv4_address: 172.28.5.21
    env_file:
      - ./config/app.${ENV}.env
    volumes:
      - ./config/app.${ENV}.env:/app/config/app.env:ro
      - app_files:/data/files:rw
      - app_logs:/data/logs:rw
    ports:
      - "5000:5000"
    restart: unless-stopped

networks:
  internal-subnet:
    name: internal_subnet
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.5.0/24

volumes:  
  app_files:
  app_logs:
